# Generated by Django 3.0.4 on 2020-03-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(editable=False, max_length=100)),
                ('websiteName', models.CharField(max_length=255)),
            ],
        ),
    ]
