# Generated by Django 3.2 on 2021-05-02 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PortalSleuthMain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmojiReviewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uploader_info', models.CharField(editable=False, max_length=100, null=True)),
                ('websiteName', models.CharField(max_length=100)),
                ('empotion', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
