# Generated by Django 3.0.4 on 2020-03-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalSleuthMain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='categoryName',
            field=models.CharField(max_length=255),
        ),
    ]
